// eslint-disable-next-line no-shadow
export enum OfferErrors {
  REQUIRED_TITLE = 'OFFER.REQUIRED_TITLE',
  REQUIRED_MESSAGE = 'OFFER.REQUIRED_MESSAGE',
  REQUIRED_VALUE = 'OFFER.REQUIRED_VALUE',
  REQUIRED_SERVICE = 'OFFER.REQUIRED_SERVICE',
  REQUIRED_STATUS = 'OFFER.REQUIRED_STATUS',
  VALUE_MUST_BE_HIGHER_THAN_SERVICE_MIN_VALUE = 'OFFER.VALUE_MUST_BE_HIGHER_THAN_SERVICE_MIN_VALUE',
  ALREADY_EXISTS_FOR_THIS_USER_AND_SERVICE = 'OFFER.ALREADY_EXISTS_FOR_THIS_USER_AND_SERVICE',
  YOU_CANT_MAKE_AN_OFFER_FOR_YOUR_SERVICE = 'OFFER.YOU_CANT_MAKE_AN_OFFER_FOR_YOUR_SERVICE',
  NOT_FOUND = 'OFFER.NOT_FOUND',
  YOU_CAN_ONLY_DELETE_YOUR_OWN_OFFER = 'OFFER.YOU_CAN_ONLY_DELETE_YOUR_OWN_OFFER',
  YOU_CAN_ONLY_UPDATE_YOUR_OWN_OFFER = 'OFFER.YOU_CAN_ONLY_UPDATE_YOUR_OWN_OFFER',
  STATUS_MUST_BE_DONE = 'OFFER.STATUS_MUST_BE_DONE',
  STATUS_MUST_BE_FINISHED = 'OFFER.STATUS_MUST_BE_FINISHED',
  INVALID_THUMBS_UP = 'OFFER.INVALID_THUMBS_UP',
}
