// eslint-disable-next-line no-shadow
export enum ServiceErrors {
  REQUIRED_NAME = 'SERVICE.REQUIRED_NAME',
  REQUIRED_MIN_VALUE = 'SERVICE.REQUIRED_MIN_VALUE',
  REQUIRED_CATEGORY_ID = 'SERVICE.REQUIRED_CATEGORY_ID',
}
