// eslint-disable-next-line no-shadow
export enum ServiceErrors {
  REQUIRED_NAME = 'SERVICE.REQUIRED_NAME',
  REQUIRED_MIN_VALUE = 'SERVICE.REQUIRED_MIN_VALUE',
  REQUIRED_CATEGORY_ID = 'SERVICE.REQUIRED_CATEGORY_ID',
  INVALID_WORKER = ' SERVICE.INVALID_WORKER',
  NOT_A_WORKER = 'SERVICE.NOT_A_WORKER',
  ALREADY_EXISTS = 'SERVICE.ALREADY_EXISTS',
  NOT_FOUND = 'SERVICE.NOT_FOUND',
  REQUIRED_DESCRIPTION = 'SERVICE.REQUIRED_DESCRIPTION',
}
