// eslint-disable-next-line no-shadow
export enum UserErrors {
  EMAIL_ALREADY_IN_USE = 'USER.EMAIL_ALREADY_IN_USE',
  REQUIRED_NAME = 'USER.REQUIRED_NAME',
  REQUIRED_EMAIL = 'USER.REQUIRED_EMAIL',
  REQUIRED_PASSWORD = 'USER.REQUIRED_PASSWORD',
  INVALID_PASSWORD = 'USER.INVALID_PASSWORD',
  REQUIRED_PASSWORD_CONFIRMATION = 'USER.REQUIRED_PASSWORD_CONFIRMATION',
  INVALID_PASSWORD_CONFIRMATION = 'USER.INVALID_PASSWORD_CONFIRMATION',
  ACCOUNT_NOT_FOUND = 'USER.ACCOUNT_NOT_FOUND',
  WRONG_PASSWORD = 'USER.WRONG_PASSWORD',
  REQUIRED_CITY = 'USER.REQUIRED_CITY',
  INVALID_EMAIL = 'USER.INVALID_EMAIL',
}
